export const AUTHORITIES = [
  'TOP_DASHBOARD', // ダッシュボード/TOP
  'EU_CONSTRUCTION', // 工事検索／一覧
  'EU_CONSTRUCTION_NEW', // 工事追加
  'EU_CONSTRUCTION_DETAIL', // 工事詳細
  'EU_CONSTRUCTION_INFO_SETTING',
  'EU_CONSTRUCTION_EDIT', // 工事変更
  'EU_CONSTRUCTION_DASHBOARD', // 工事ダッシュボード
  'EU_CONSTRUCTION_STRUCTURE', // 工事体制
  'EU_CONSTRUCTION_COSTMANAGE', // 原価管理
  'EU_CONSTRUCTION_COST_CATEGORIES',
  'EU_CONSTRUCTION_OVERVIEW_NEW', // 工事概要
  'EU_CONSTRUCTION_OVERVIEW',
  'EU_CONSTRUCTION_OVERVIEW_EDIT',
  'EU_CONSTRUCTION_ESTIMATE', // 工事見積
  'EU_CONSTRUCTION_SUMMARY',
  'EU_CONSTRUCTION_COST_CSVIMPORT',
  'EU_CONSTRUCTION_COST_DETAIL_REGISTRATION_DIALOG',
  'EU_CONSTRUCTION_COST_EXCEL_IMPORT',
  'EU_CONSTRUCTION_COST_NEW',
  'EU_CONSTRUCTION_COST_SUMMARY',
  'EU_CONSTRUCTION_ADD_INC_DEC',
  'EU_CONSTRUCTION_ADD_INC_DEC_NEW',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_DETAIL',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_APPLICATION',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_APPROVALS',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES',
  'EU_COOPERATOR_EDIT',
  'EU_COOPERATOR_DETAIL',
  'EU_COOPERATORS',
  'EU_COOPERATORS_NEW',
  'EU_CUSTOMERS_EDIT',
  'EU_CUSTOMERS_DETAILS',
  'EU_CUSTOMERS',
  'EU_CUSTOMERS_NEW',
  'EU_MANAGE',
  'EU_PENDING_APP',
  'EU_REQUESTS_DETAILS',
  'EU_REQUESTS_APPLICATIONS_EDIT',
  'EU_REQUESTS_APPLICATIONS',
  'EU_REQUESTS_APPLICATIONS_NEW',
  'EU_REQUESTS_APPROVALS',
  'EU_POSTS',
  'EU_CONSTRUCTION_STATUS_TABLE',
  'EU_ORDERS',
  'EU_WORKFLOW_SEARCH',
  'EU_WORKFLOW_APPROVALS',
  'EM_WORKFLOW',
  'EU_MAINTENCE',
  'EU_BUL_RECORD',
  'EU_HET_CALL',
  // labels
  'EU_CONSTRUCTION_LABEL',
  'EU_CUSTOMER_LABEL',
  'EU_COOPERATOR_LABEL',
  'EU_ADVANCE_EXPENSE_SETTLEMENT_LABEL',
  'EU_APP_REQUEST_LABEL',
  'EM_APPROVAL_ROUTE_REGISTRATION',
  'EM_EXPENSE_CAPTURE',
  'EM_MANAGE_LABEL',
  'CU_ASSESSMENTS',
  'CU_BASIC_INFO',
  'CU_PAYMENTS',
] as const;

export const EU_AUTHORITIES = [
  'TOP_DASHBOARD', // ダッシュボード/TOP
  'EU_CONSTRUCTION', // 工事検索／一覧
  'EU_CONSTRUCTION_NEW', // 工事追加
  'EU_CONSTRUCTION_DETAIL', // 工事詳細
  'EU_CONSTRUCTION_INFO_SETTING',
  'EU_CONSTRUCTION_EDIT', // 工事変更
  'EU_CONSTRUCTION_DASHBOARD', // 工事ダッシュボード
  'EU_CONSTRUCTION_STRUCTURE', // 工事体制
  'EU_CONSTRUCTION_COSTMANAGE', // 原価管理
  'EU_CONSTRUCTION_COST_CATEGORIES',
  'EU_CONSTRUCTION_OVERVIEW_NEW', // 工事概要
  'EU_CONSTRUCTION_OVERVIEW',
  'EU_CONSTRUCTION_OVERVIEW_EDIT',
  'EU_CONSTRUCTION_ESTIMATE', // 工事見積
  'EU_CONSTRUCTION_SUMMARY',
  'EU_CONSTRUCTION_COST_CSVIMPORT',
  'EU_CONSTRUCTION_COST_DETAIL_REGISTRATION_DIALOG',
  'EU_CONSTRUCTION_COST_EXCEL_IMPORT',
  'EU_CONSTRUCTION_COST_NEW',
  'EU_CONSTRUCTION_COST_SUMMARY',
  'EU_CONSTRUCTION_ADD_INC_DEC',
  'EU_CONSTRUCTION_ADD_INC_DEC_NEW',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_DETAIL',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_APPLICATION',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES_APPROVALS',
  'EU_CONSTRUCTION_EMPLOYEE_EXPENSES',
  'EU_COOPERATOR_EDIT',
  'EU_COOPERATOR_DETAIL',
  'EU_COOPERATORS',
  'EU_COOPERATORS_NEW',
  'EU_CUSTOMERS_EDIT',
  'EU_CUSTOMERS_DETAILS',
  'EU_CUSTOMERS',
  'EU_CUSTOMERS_NEW',
  'EU_MANAGE',
  'EU_PENDING_APP',
  'EU_REQUESTS_DETAILS',
  'EU_REQUESTS_APPLICATIONS_EDIT',
  'EU_REQUESTS_APPLICATIONS',
  'EU_REQUESTS_APPLICATIONS_NEW',
  'EU_REQUESTS_APPROVALS',
  'EU_POSTS',
  'EU_CONSTRUCTION_STATUS_TABLE',
  'EU_ORDERS',
  'EU_WORKFLOW_SEARCH',
  'EU_WORKFLOW_APPROVALS',
  'EU_MAINTENCE',
  'EU_BUL_RECORD',
  'EU_HET_CALL',
  'EU_INVOICE',
] as const;

export const EM_AUTHORITIES = [
  'TOP_DASHBOARD', // ダッシュボード/TOP
  'EM_APPROVAL_ROUTE_REGISTRATION',
  'EM_EXPENSE_CAPTURE',
  'EM_WORKFLOW',
] as const;

export const CU_AUTHORITIES = [
  'CU_DASHBOARD', // 協力会社ダッシュボード/TOP
  'CU_ASSESSMENTS_EDIT',
  'CU_ASSESSMENTS',
  'CU_BASIC_INFO',
  'CU_PAYMENTS',
  'CU_RESET_PASSWORD_CONFIRMATION',
  'CU_COP_RESET_PASSWORD',
] as const;
