// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { ApplicationDetail } from '@/interfaces/applicationDetail'

export const APPLICATION_DETAIL_LIST = [
  {
    id: 1,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expenseCharge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 2,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expenseCharge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 3,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expenseCharge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 4,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 5,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 6,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 7,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 8,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 9,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  },
  {
    id: 10,
    status: 'テキスト',
    application_date: 'YYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9000,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    approval_no: 99999,
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇',
    approver_1: '承認者A',
    approver_2: '承認者B',
    purchase_transportation: 'テキスト',
    payday: 'YYYY/MM/DD',
    expense_charge: '費用負担部署',
    amount: 9999,
  }

]

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ApplicationDetail[]>
) {
  res.status(200).json(APPLICATION_DETAIL_LIST)
}
