// Next.js API route support: https://nextjs.org/docs/apiYYYY/MM/DDroutes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { Application } from '@/interfaces/application'

export const APPLICATION_LIST = [
  {
    id: 1,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 2,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 3,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 4,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 5,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 6,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 7,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 8,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 9,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },
  {
    id: 10,
    status: 'テキスト',
    application_date: 'YYYY/MM/DD',
    application_no: 99999,
    expense_name: 'テキスト',
    account_subject_1: 'テキスト',
    account_subject_2: 'テキスト',
    purchase: 'テキスト',
    purchase_amount: 9999,
    transportation: 'テキスト',
    transportation_amount: 9999,
    payment: 'テキスト',
    destination: 'テキスト',
    construction_code: 9999,
    reason: 'テキスト',
    receipt: '〇'
  },

]

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Application[]>
) {
  res.status(200).json(APPLICATION_LIST)
}
