import { NextApiRequest, NextApiResponse } from 'next';
import { ApprovalRequest } from '@/interfaces/approval_request';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ApprovalRequest[]>,
) {
  const approvalData = [
    {
      id: 1,
      status: '承認待ち',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 2,
      status: '承認取消',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 3,
      status: '下書き',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 4,
      status: '却下',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 5,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 6,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 7,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 8,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 9,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 10,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 11,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 12,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 13,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 14,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 15,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 16,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 17,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 18,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 19,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 20,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 21,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 22,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 23,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 24,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 25,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 26,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'XXXX XXXX',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 27,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'YYYY YYYY',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 28,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'ZZZ ZZZ',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 29,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'AAAA AAAA',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
    {
      id: 30,
      status: '承認',
      approval_num: 'T-20220801',
      approval_name: 'CCCC CCCC',
      subject: 'AAAAA',
      authorizer: '山本次',
      application_dt: '2022-01-17',
    },
  ];
  res.status(200).json(approvalData);
}
