/* eslint-disable @typescript-eslint/no-explicit-any */
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';
// import { CostManageMinorItemTypeNew } from '@/components/constructions/costManage/costManageMinorItem';

export const costManageMinorItems = [
  // {
  //   rowLevel: 'total',
  //   isChecked: false,
  //   isCheckedMenu: false,
  //   assessStatus: '',
  //   operation: '',
  //   minorItem: '中項目工事合計',
  //   detailRemark: '',
  //   quantitySettlementEstimate: '',
  //   unitSettlementEstimate: '',
  //   unitPriceSettlementEstimate: '',
  //   settlementEstimate: 9775400,
  //   quantityCostManage: 0,
  //   unitCostManage: '',
  //   unitPriceCostManage: 0,
  //   assumedCost: 9775400,
  //   quantityWorkingBudget: 0,
  //   unitWorkingBudget: '',
  //   unitPriceWorkingBudget: 0,
  //   workingBudget: 9775400,
  //   quantityOrderAmount: 0,
  //   unitOrderAmount: '',
  //   unitPriceOrderAmount: 0,
  //   orderAmount: 9775400,
  //   quantityAssessed: 0,
  //   unitAssessed: '',
  //   unitPriceAssessed: 0,
  //   assessed: 9775400,
  //   prospect: 750000,
  //   quantityTotalExpectCost: 0,
  //   unitTotalExpectCost: '',
  //   unitPriceTotalExpectCost: 0,
  //   totalExpectCost: 9775400,
  //   status: '',
  //   cooperatingCompany: '',
  //   rate: '23.5%',
  // },
  {
    rowLevel: 'subTotal-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: 'AAA工事',
    detailRemark: '',
    quantitySettlementEstimate: '',
    unitSettlementEstimate: '',
    unitPriceSettlementEstimate: '',
    settlementEstimate: 8234800,
    quantityCostManage: 0,
    unitCostManage: '',
    unitPriceCostManage: 0,
    assumedCost: 8234800,
    quantityWorkingBudget: 0,
    unitWorkingBudget: '',
    unitPriceWorkingBudget: 0,
    workingBudget: 8234800,
    quantityOrderAmount: 0,
    unitOrderAmount: '',
    unitPriceOrderAmount: 0,
    orderAmount: 8234800,
    quantityAssessed: 0,
    unitAssessed: '',
    unitPriceAssessed: 0,
    assessed: 8234800,
    prospect: 750000,
    quantityTotalExpectCost: 0,
    unitTotalExpectCost: '',
    unitPriceTotalExpectCost: 0,
    totalExpectCost: 8234800,
    status: '発注済',
    cooperatingCompany: '協力会社',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '100%',
    operation: '',
    minorItem: '',
    detailRemark: 'Fc=18N-18',
    quantitySettlementEstimate: '11.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 206800,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 206800,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 206800,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 206800,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 206800,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 206800,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '',
    detailRemark: 'Fc=21N-15→Fm=',
    quantitySettlementEstimate: '218.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 4360000,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 4360000,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 4360000,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 4360000,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 4360000,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 4360000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '100%',
    operation: '',
    minorItem: '基複コンクリート',
    detailRemark: 'Fc=24N-15→Fm=',
    quantitySettlementEstimate: '118.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 2430800,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 2430800,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 2430800,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 2430800,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 2430800,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 2430800,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '100%',
    operation: '',
    minorItem: '1段位よりコンクリート',
    detailRemark: 'Fc=24N-15→Fm=',
    quantitySettlementEstimate: '118.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 309000,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 309000,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 309000,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 309000,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 309000,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 309000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '100%',
    operation: '',
    minorItem: '根底コンクリート',
    detailRemark: 'Fc=24N-15→Fm=',
    quantitySettlementEstimate: '118.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 82400,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 82400,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 82400,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 82400,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 82400,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 82400,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '通しモルタル',
    detailRemark: '',
    quantitySettlementEstimate: '118.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '18.800',
    settlementEstimate: 53000,
    quantityCostManage: 11.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 18800,
    assumedCost: 53000,
    quantityWorkingBudget: 11.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 18800,
    workingBudget: 53000,
    quantityOrderAmount: 11.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 18800,
    orderAmount: 53000,
    quantityAssessed: 11.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 18800,
    assessed: 53000,
    prospect: 750000,
    quantityTotalExpectCost: 11.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 18800,
    totalExpectCost: 53000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '100%',
    operation: '',
    minorItem: 'ブンプ車損料',
    detailRemark: '',
    quantitySettlementEstimate: '5.00',
    unitSettlementEstimate: '回',
    unitPriceSettlementEstimate: '90.00',
    settlementEstimate: 450000,
    quantityCostManage: 5.0,
    unitCostManage: '回',
    unitPriceCostManage: 90000,
    assumedCost: 450000,
    quantityWorkingBudget: 5.0,
    unitWorkingBudget: '回',
    unitPriceWorkingBudget: 90000,
    workingBudget: 450000,
    quantityOrderAmount: 5.0,
    unitOrderAmount: '回',
    unitPriceOrderAmount: 90000,
    orderAmount: 450000,
    quantityAssessed: 5.0,
    unitAssessed: '回',
    unitPriceAssessed: 90000,
    assessed: 450000,
    prospect: 750000,
    quantityTotalExpectCost: 5.0,
    unitTotalExpectCost: '回',
    unitPriceTotalExpectCost: 90000,
    totalExpectCost: 450000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: 'ブンプ返し費',
    detailRemark: '',
    quantitySettlementEstimate: '5.00',
    unitSettlementEstimate: '回',
    unitPriceSettlementEstimate: '90.00',
    settlementEstimate: 450000,
    quantityCostManage: 5.0,
    unitCostManage: '回',
    unitPriceCostManage: 90000,
    assumedCost: 450000,
    quantityWorkingBudget: 5.0,
    unitWorkingBudget: '回',
    unitPriceWorkingBudget: 90000,
    workingBudget: 450000,
    quantityOrderAmount: 5.0,
    unitOrderAmount: '回',
    unitPriceOrderAmount: 90000,
    orderAmount: 450000,
    quantityAssessed: 5.0,
    unitAssessed: '回',
    unitPriceAssessed: 90000,
    assessed: 450000,
    prospect: 750000,
    quantityTotalExpectCost: 5.0,
    unitTotalExpectCost: '回',
    unitPriceTotalExpectCost: 90000,
    totalExpectCost: 450000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-1',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '圧送料',
    detailRemark: '',
    quantitySettlementEstimate: '36.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '90.00',
    settlementEstimate: 292800,
    quantityCostManage: 5.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 90000,
    assumedCost: 292800,
    quantityWorkingBudget: 5.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 90000,
    workingBudget: 292800,
    quantityOrderAmount: 5.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 90000,
    orderAmount: 292800,
    quantityAssessed: 5.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 90000,
    assessed: 292800,
    prospect: 750000,
    quantityTotalExpectCost: 5.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 90000,
    totalExpectCost: 292800,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'subTotal-2',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: 'BBB工事',
    detailRemark: '',
    quantitySettlementEstimate: '',
    unitSettlementEstimate: '',
    unitPriceSettlementEstimate: '',
    settlementEstimate: 980600,
    quantityCostManage: 0,
    unitCostManage: '',
    unitPriceCostManage: 0,
    assumedCost: 980600,
    quantityWorkingBudget: 0,
    unitWorkingBudget: '',
    unitPriceWorkingBudget: 0,
    workingBudget: 980600,
    quantityOrderAmount: 0,
    unitOrderAmount: '',
    unitPriceOrderAmount: 0,
    orderAmount: 980600,
    quantityAssessed: 0,
    unitAssessed: '',
    unitPriceAssessed: 0,
    assessed: 980600,
    prospect: 750000,
    quantityTotalExpectCost: 0,
    unitTotalExpectCost: '',
    unitPriceTotalExpectCost: 0,
    totalExpectCost: 980600,
    status: '見込み',
    cooperatingCompany: '協力会社',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-2',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '',
    detailRemark: '20kg/m3',
    quantitySettlementEstimate: '237.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '2,000',
    settlementEstimate: 474000,
    quantityCostManage: 237.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 2000,
    assumedCost: 474000,
    quantityWorkingBudget: 237.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 2000,
    workingBudget: 474000,
    quantityOrderAmount: 237.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 2000,
    orderAmount: 474000,
    quantityAssessed: 237.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 2000,
    assessed: 474000,
    prospect: 750000,
    quantityTotalExpectCost: 237.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 2000,
    totalExpectCost: 474000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-2',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '',
    detailRemark: '2kg/m3',
    quantitySettlementEstimate: '237.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '2,000',
    settlementEstimate: 355500,
    quantityCostManage: 237.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 2000,
    assumedCost: 355500,
    quantityWorkingBudget: 237.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 2000,
    workingBudget: 355500,
    quantityOrderAmount: 237.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 2000,
    orderAmount: 355500,
    quantityAssessed: 237.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 2000,
    assessed: 355500,
    prospect: 750000,
    quantityTotalExpectCost: 237.0,
    unitTotalExpectCost: 'm3',
    unitPriceTotalExpectCost: 2000,
    totalExpectCost: 355500,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-2',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '役入管理費',
    detailRemark: '',
    quantitySettlementEstimate: '2.00',
    unitSettlementEstimate: '回',
    unitPriceSettlementEstimate: '2,000',
    settlementEstimate: 355500,
    quantityCostManage: 237.0,
    unitCostManage: '回',
    unitPriceCostManage: 2000,
    assumedCost: 355500,
    quantityWorkingBudget: 237.0,
    unitWorkingBudget: '回',
    unitPriceWorkingBudget: 2000,
    workingBudget: 355500,
    quantityOrderAmount: 237.0,
    unitOrderAmount: '回',
    unitPriceOrderAmount: 2000,
    orderAmount: 355500,
    quantityAssessed: 237.0,
    unitAssessed: '回',
    unitPriceAssessed: 2000,
    assessed: 355500,
    prospect: 750000,
    quantityTotalExpectCost: 237.0,
    unitTotalExpectCost: '回',
    unitPriceTotalExpectCost: 2000,
    totalExpectCost: 355500,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-2',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: '圧送料',
    detailRemark: '',
    quantitySettlementEstimate: '366.00',
    unitSettlementEstimate: 'm3',
    unitPriceSettlementEstimate: '2,000',
    settlementEstimate: 355500,
    quantityCostManage: 237.0,
    unitCostManage: 'm3',
    unitPriceCostManage: 2000,
    assumedCost: 355500,
    quantityWorkingBudget: 237.0,
    unitWorkingBudget: 'm3',
    unitPriceWorkingBudget: 2000,
    workingBudget: 355500,
    quantityOrderAmount: 237.0,
    unitOrderAmount: 'm3',
    unitPriceOrderAmount: 2000,
    orderAmount: 355500,
    quantityAssessed: 237.0,
    unitAssessed: 'm3',
    unitPriceAssessed: 2000,
    assessed: 355500,
    prospect: 750000,
    quantityTotalExpectCost: 237.0,
    unitTotalExpectCost: '回',
    unitPriceTotalExpectCost: 2000,
    totalExpectCost: 355500,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'subTotal-3',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '労務費',
    operation: '',
    minorItem: 'CCC工事',
    detailRemark: '',
    quantitySettlementEstimate: '',
    unitSettlementEstimate: '',
    unitPriceSettlementEstimate: '',
    settlementEstimate: 540000,
    quantityCostManage: 0,
    unitCostManage: '',
    unitPriceCostManage: 0,
    assumedCost: 540000,
    quantityWorkingBudget: 0,
    unitWorkingBudget: '',
    unitPriceWorkingBudget: 0,
    workingBudget: 540000,
    quantityOrderAmount: 0,
    unitOrderAmount: '',
    unitPriceOrderAmount: 0,
    orderAmount: 540000,
    quantityAssessed: 0,
    unitAssessed: '',
    unitPriceAssessed: 0,
    assessed: 540000,
    prospect: 750000,
    quantityTotalExpectCost: 0,
    unitTotalExpectCost: '',
    unitPriceTotalExpectCost: 0,
    totalExpectCost: 540000,
    status: '見込み',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-3',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: 'コンクリート打設手間',
    detailRemark: '',
    quantitySettlementEstimate: '30',
    unitSettlementEstimate: '人',
    unitPriceSettlementEstimate: '18,000',
    settlementEstimate: 540000,
    quantityCostManage: 30,
    unitCostManage: '人',
    unitPriceCostManage: 18000,
    assumedCost: 540000,
    quantityWorkingBudget: 30,
    unitWorkingBudget: '人',
    unitPriceWorkingBudget: 18000,
    workingBudget: 540000,
    quantityOrderAmount: 30,
    unitOrderAmount: '人',
    unitPriceOrderAmount: 18000,
    orderAmount: 540000,
    quantityAssessed: 30,
    unitAssessed: '人',
    unitPriceAssessed: 18000,
    assessed: 540000,
    prospect: 750000,
    quantityTotalExpectCost: 30,
    unitTotalExpectCost: '人',
    unitPriceTotalExpectCost: 18000,
    totalExpectCost: 540000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'subTotal-4',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '経費',
    operation: '',
    minorItem: 'DDD工事',
    detailRemark: '',
    quantitySettlementEstimate: '',
    unitSettlementEstimate: '',
    unitPriceSettlementEstimate: '',
    settlementEstimate: 0,
    quantityCostManage: 0,
    unitCostManage: '',
    unitPriceCostManage: 0,
    assumedCost: 0,
    quantityWorkingBudget: 0,
    unitWorkingBudget: '',
    unitPriceWorkingBudget: 0,
    workingBudget: 0,
    quantityOrderAmount: 0,
    unitOrderAmount: '',
    unitPriceOrderAmount: 0,
    orderAmount: 0,
    quantityAssessed: 0,
    unitAssessed: '',
    unitPriceAssessed: 0,
    assessed: 0,
    prospect: 750000,
    quantityTotalExpectCost: 0,
    unitTotalExpectCost: '',
    unitPriceTotalExpectCost: 0,
    totalExpectCost: 0,
    status: '見込み',
    cooperatingCompany: '',
    rate: '23.5%',
  },
  {
    rowLevel: 'item-4',
    isChecked: false,
    isCheckedMenu: false,
    assessStatus: '',
    operation: '',
    minorItem: 'コンクリート打設手間',
    detailRemark: '',
    quantitySettlementEstimate: '30',
    unitSettlementEstimate: '人',
    unitPriceSettlementEstimate: '18,000',
    settlementEstimate: 540000,
    quantityCostManage: 30,
    unitCostManage: '人',
    unitPriceCostManage: 18000,
    assumedCost: 540000,
    quantityWorkingBudget: 30,
    unitWorkingBudget: '人',
    unitPriceWorkingBudget: 18000,
    workingBudget: 540000,
    quantityOrderAmount: 30,
    unitOrderAmount: '人',
    unitPriceOrderAmount: 18000,
    orderAmount: 540000,
    quantityAssessed: 30,
    unitAssessed: '人',
    unitPriceAssessed: 18000,
    assessed: 540000,
    prospect: 750000,
    quantityTotalExpectCost: 30,
    unitTotalExpectCost: '人',
    unitPriceTotalExpectCost: 18000,
    totalExpectCost: 540000,
    status: '',
    cooperatingCompany: '',
    rate: '23.5%',
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any[]>,
) {
  res.status(200).json(costManageMinorItems);
}
