export type ConstructionInformationSettingsDetail = {
  id: number;
  construction_id: number;
  value_creation_sheet: string;
  workshop_folder: string;
  design_drawing: string;
  working_diagram: string;
  work_schedule: string;
  photo_management: string;
  index: string;
  buildee: string;
  spider_plus: string;  
  safey: string;
  contract: string;
  contract_drawing: string;
  place_on: string;
  cooperator_estimate: string;
  movie: string;
  map: string;
  rule: string;
};

export type TypeConstructionInformationSetting = {
  id: number;
  construction_id: number;
  value_creation_sheet: string;
  workshop_folder: string;
  design_drawing: string;
  working_diagram: string;
  work_schedule: string;
  photo_management: string;
  index: string;
  buildee: string;
  spider_plus: string;
  safey: string;
  contract: string;
  contract_drawing: string;
  place_on: string;
  cooperator_estimate: string;
  movie: string;
  map: string;
  rule: string;
};
